CREATE TABLE T_ROL ( 
  ROL_ID    		NUMBER			CONSTRAINT ROL_ID_NO_NULO	NOT NULL,
  ROL_NOMBRE       	VARCHAR2(20)    CONSTRAINT ROL_NOMBRE_NO_NULO NOT NULL
);
--
COMMENT ON TABLE T_ROL IS 'Tabla de roles de usuario';
COMMENT ON COLUMN T_ROL.ROL_ID IS 'Secuencia de identificación del usuario';
COMMENT ON COLUMN T_ROL.ROL_NOMBRE IS 'Nombre del usuario';
--

ALTER TABLE T_ROL ADD (
CONSTRAINT ROL_PKEY_ROL_ID PRIMARY KEY (ROL_ID)
USING INDEX);