CREATE TABLE T_USUARIO ( 
  USUARIO_ID    		NUMBER			CONSTRAINT USUARIO_ID_NOT_NULL	NOT NULL,
  USUARIO_ROL       	NUMBER		    CONSTRAINT USUARIO_ROL_NOT_NULL NOT NULL,
  USUARIO_NOMBRE       	VARCHAR2(20)    CONSTRAINT USUARIO_NOMBRE_NOT_NULL NOT NULL,
  USUARIO_ACTIVO       	VARCHAR2(1)		CONSTRAINT USUARIO_ACTIVO_NOT_NULL NOT NULL
);
--
COMMENT ON TABLE T_USUARIO IS 'Tabla de USUARIOes de usuario';
COMMENT ON COLUMN T_USUARIO.USUARIO_ID IS 'Secuencia de identificación del usuario';
COMMENT ON COLUMN T_USUARIO.USUARIO_ROL IS 'Rol asignado al usuario';
COMMENT ON COLUMN T_USUARIO.USUARIO_NOMBRE IS 'Nombre del usuario';
COMMENT ON COLUMN T_USUARIO.USUARIO_ACTIVO IS 'Estado del usuario en el sistema';
--
--
ALTER TABLE T_USUARIO ADD (
CONSTRAINT USUARIO_PKEY_USUARIO_ID PRIMARY KEY (USUARIO_ID)
USING INDEX);
--
ALTER TABLE T_USUARIO
ADD CONSTRAINT USUARIO_FKEY_ROL
FOREIGN KEY (USUARIO_ROL)
REFERENCES T_ROL(ROL_ID);
--
ALTER TABLE T_USUARIO
ADD CONSTRAINT CHECK_USUARIO_ACTIVO
  CHECK (USUARIO_ACTIVO IN ('A', 'N'));
--